apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-config
data:
  config.json: |
    {
      "bridge": {
        "name": "{{ .Values.homebridge.name }}",
        "username": "{{ .Values.homebridge.username }}",
        "port": {{ .Values.homebridge.port }},
        "pin": "{{ .Values.homebridge.pin }}"
      },
      "description": "{{ .Values.homebridge.description }}",
      "accessories": [
        {
          "accessory": "VizioDisplay",
          "name": "{{ .Values.accessories.vizioTv.name }}",
          "address": "{{ .Values.accessories.vizioTv.ipAddress }}",
          "token": "{{ .Values.accessories.vizioTv.token }}"
        },
        {
          "accessory": "GarageDoorOpener",
          "name": "{{ .Values.accessories.garageDoorOpener.name }}",
          "openURL": "{{ .Values.accessories.garageDoorOpener.openUrl }}",
          "closeURL": "{{ .Values.accessories.garageDoorOpener.closeUrl }}",
          "http_method": "{{ .Values.accessories.garageDoorOpener.httpMethod }}"
        }
      ],
      "platforms": [
        {
          "platform": "Camera-ffmpeg",
          {{ .Files.Get "cam-config.json" | indent 11 }}
        }
      ]

    }

  package.json: |
    {
      "private": true,
      "description": "This file keeps track of which plugins should be installed.",
      "dependencies": {
        "homebridge-camera-ffmpeg": "^0.1.13",
        "homebridge-http-garage": "1.2.4",
        "homebridge-vizio": "^1.0.1"
      }
    }
